apiVersion: v1
kind: Service
metadata:
  name: opl-star-app
  labels:
    app: opl-star-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
