apiVersion: apps/v1
kind: Deployment
metadata:
  name: opl-star-app
  labels:
    app: opl-star-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: opl-star-app
  template:
    metadata:
      name: opl-star-app
      labels:
        app: opl-star-app
    spec:
      containers:
        - image: opl242/opl_star_app:v4
          name: opl-star-app
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "1Gi"
              cpu: "100m"
            limits:
              memory: "10Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 45
            periodSeconds: 3