apiVersion: v1
kind: Pod
metadata:
  name: opl-star-app
  labels:
    app: opl-star-app
spec:
  containers:
    - image: opl242/opl_star_app
      name: opl-star-app
      ports:
        - containerPort: 5000
      