image:
  tag: pr-1

service:
  port: 5000
  targetPort: 5000
  type: LoadBalancer

replicas: 4
maxSurge: 50%
minUnavailable: 50%

resources:
  memory: "1Gi"
  cpu: "100m"
  max_memory: "10Gi"
  max_cpu: "500m"

